name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed
  $CHANGES
autolabeler:
  # Adds a GitHub label to the PR
  # The branch name of the PR must start with 'type/'
  # This makes a cleaner changelog with the release-drafter github action
  # As the titles can be just the commit message / whatever title

  - label: "chore"
    branch:
      - '/chore\/.+/'

  - label: "bug"
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
      - '/bugfix\/.+/'

  - label: "feature"
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'

  - label: "docs"
    branch:
      - '/docs\/.+/'
      - '/documentation\/.+/'

  - label: "test"
    branch:
      - '/test\/.+/'
      - '/tests\/.+/'
      - '/testing\/.+/'

categories:
  - title: "🚀 Features"
    label: "feature"

  - title: "🐛 Bug Fixes"
    labell: "bug"

  - title: "🧰 Maintenance"
    label: "chore"

  - title: "📝 Documentation"
    label: "docs"

  - title: "🧪 Tests"
    label: "test"

exclude-labels:
  - "skip-changelog"
